/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 서버와 DB가 살아 있는지 확인한다 (DB 연결이 끊기면 503) */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/issues/{sn}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 1건 조회. 없으면 404 */
        get: operations["read"];
        put?: never;
        post?: never;
        /** 삭제 (IssueDeleted). 성공 204, 없으면 404. 속한 태스크는 남고 issue_sn만 비워진다 */
        delete: operations["remove"];
        options?: never;
        head?: never;
        /** 부분 수정 (UpdateIssue → IssueUpdated). 없으면 404, 모르는 status면 422 */
        patch: operations["update"];
        trace?: never;
    };
    "/issues/{sn}/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 이슈의 태스크 목록 (번호순) */
        get: operations["list"];
        put?: never;
        /** 태스크 생성 (CreateTask → TaskCreated). 이슈가 없으면 404 */
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/members/{sn}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 멤버 1건 조회. 없으면 404 */
        get: operations["member"];
        put?: never;
        post?: never;
        /** 멤버 삭제 (MemberDeleted). 멤버 프로필도 지운다. Run · 리뷰 등 기록이 있으면 409 (보관 = status archived) */
        delete: operations["delete"];
        options?: never;
        head?: never;
        /** 멤버 부분 수정 (MemberUpdated). 모르는 상태는 422, 없으면 404 */
        patch: operations["edit"];
        trace?: never;
    };
    "/profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 프로필 목록 (번호순). `kind`로 거른다 */
        get: operations["list"];
        put?: never;
        /** 프로필 생성 (ProfileCreated) */
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profiles/{sn}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 1건 조회. 없으면 404 */
        get: operations["read"];
        put?: never;
        post?: never;
        /** 삭제 (ProfileDeleted). 성공 204, 없으면 404, 멤버가 쓰는 중이면 409 (하위 설정은 CASCADE) */
        delete: operations["remove"];
        options?: never;
        head?: never;
        /** 부분 수정 (ProfileUpdated). 없으면 404 */
        patch: operations["update"];
        trace?: never;
    };
    "/profiles/{sn}/caps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 하위 매핑 조회: 스킬 · MCP · 도구 정책 (편집은 별도 Task). 프로필이 없으면 404 */
        get: operations["caps"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 목록 (탭 순서 sort, 같으면 번호순) */
        get: operations["list"];
        put?: never;
        /** 생성 후 DB 기본값까지 채운 행을 201로 돌려준다 */
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{sn}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 1건 조회. 없으면 404 */
        get: operations["read"];
        put?: never;
        post?: never;
        /** 삭제. 성공 204, 없으면 404 (하위 데이터는 스키마의 ON DELETE 규칙을 따른다) */
        delete: operations["remove"];
        options?: never;
        head?: never;
        /** 부분 수정 후 최신 행을 돌려준다. 없으면 404 */
        patch: operations["update"];
        trace?: never;
    };
    "/projects/{sn}/issues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 프로젝트의 이슈 목록 (번호순) */
        get: operations["list"];
        put?: never;
        /** 이슈 생성 (CreateIssue → IssueCreated). 프로젝트가 없으면 404 */
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{sn}/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 프로젝트 태스크 목록 (Kanban용). `status`로 거르고 queue_sort → 번호순 */
        get: operations["board"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{sn}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 1건 조회. 없으면 404 */
        get: operations["read"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{sn}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 승인 (ApproveRun → RunApproved). Run은 completed, 태스크는 done */
        post: operations["approve"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{sn}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 반려 (RejectRun → RunRejected). Run은 failed(rejected), 태스크는 in_progress로 돌아가고 tbl_review에 반려가 쌓인다 (round = 반려 횟수). 재실행은 retry */
        post: operations["reject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{sn}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 재시도 (RetryRun → RunStarted). failed · cancelled Run에서만, 기존 Run은 그대로 두고 새 Run을 만든다 */
        post: operations["retry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{sn}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 리뷰 요청 (RequestReview → ReviewRequested). running Run과 in_progress 태스크가 함께 review로 간다 */
        post: operations["review"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{sn}/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Run의 Session 목록 (번호순) */
        get: operations["sessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{sn}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run 중지 (StopRun → RunCancelled). 끝난 Run이면 409. 태스크 상태는 그대로 둔다 */
        post: operations["stop"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{sn}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 1건 조회. 없으면 404 */
        get: operations["read"];
        put?: never;
        post?: never;
        /** 삭제 (TaskDeleted). 성공 204, 없으면 404 */
        delete: operations["remove"];
        options?: never;
        head?: never;
        /** 부분 수정 (TaskUpdated). 상태는 못 바꾼다. 없으면 404 */
        patch: operations["update"];
        trace?: never;
    };
    "/tasks/{sn}/assign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 멤버 배정 (AssignAgent → AgentAssigned · assign_by = user). 없는 멤버 422, 보관된 멤버 409. Run은 만들지 않는다 */
        post: operations["assign"];
        /** 배정 해제 (AgentUnassigned · member_sn = NULL) */
        delete: operations["unassign"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{sn}/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 상태 이동 (MoveTask → TaskMoved). 표에 없는 전이는 409, 없는 태스크는 404 */
        post: operations["mv"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{sn}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 태스크의 Run 목록 (번호순) */
        get: operations["list"];
        put?: never;
        /** Run 시작 (StartRun → RunStarted). Run은 queued로 만들고 태스크는 in_progress. 담당 멤버가 없거나 진행 중 Run이 있으면 409 */
        post: operations["start"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 팀 목록 (sort → 번호순) */
        get: operations["list"];
        put?: never;
        /** 팀 생성 (TeamCreated) */
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams/{sn}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 팀 1건 조회. 없으면 404 */
        get: operations["read"];
        put?: never;
        post?: never;
        /** 팀 삭제 (TeamDeleted). 멤버와 멤버 프로필도 지운다. Run 기록이 있는 멤버가 있으면 409 */
        delete: operations["remove"];
        options?: never;
        head?: never;
        /** 팀 부분 수정 (TeamUpdated). 없으면 404 */
        patch: operations["update"];
        trace?: never;
    };
    "/teams/{sn}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 팀 멤버 목록 (sort → 번호순). 팀이 없으면 404 */
        get: operations["members"];
        put?: never;
        /** 멤버 추가 (MemberCreated). 템플릿이 없으면 422, draft · 보관 · live 버전 없음은 409, 템플릿 없이 role_name도 없으면 422 */
        post: operations["add"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 템플릿 목록 (보관 제외 · sort → 번호순) */
        get: operations["templates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/templates/{sn}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 템플릿 1건 조회. 없으면 404 */
        get: operations["template"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description AssignAgent 요청 본문 */
        AssignBody: {
            /**
             * Format: int64
             * @description 배정할 멤버 (Agent profile 아님)
             */
            member_sn: number;
        };
        /** @description 프로필 하위 매핑 (조회 전용) */
        Caps: {
            mcps: components["schemas"]["McpLink"][];
            skills: components["schemas"]["SkillLink"][];
            tools: components["schemas"]["ToolRule"][];
        };
        /** @description 에러 응답 본문 (OpenAPI 공통 에러 스키마) */
        ErrorBody: {
            /** @description 에러 코드 (예: not_found, invalid_ref) */
            error: string;
            /** @description 사람이 읽는 설명 */
            message: string;
        };
        /** @description health 응답 */
        Health: {
            /** @description ok | down */
            db: string;
            /** @description ok | error */
            status: string;
        };
        /** @description 이슈 (API 응답 형태) */
        Issue: {
            body?: string | null;
            close_at?: string | null;
            create_at: string;
            /** Format: int64 */
            github_number?: number | null;
            github_url?: string | null;
            /**
             * Format: int64
             * @description 화면 표시 번호 (태스크와 공용)
             */
            num: number;
            /** Format: int64 */
            parent_sn?: number | null;
            /** Format: int64 */
            project_sn: number;
            /** Format: int64 */
            sn: number;
            source: string;
            /** @description open | in_progress | done | closed */
            status: string;
            title: string;
            update_at: string;
        };
        /** @description 생성 요청 본문 */
        IssueNew: {
            body?: string | null;
            /** Format: int64 */
            parent_sn?: number | null;
            title: string;
        };
        /** @description 수정 요청 본문. 보낸 필드만 바꾼다 (이벤트 payload로도 그대로 저장된다) */
        IssuePatch: {
            body?: string | null;
            /** @description open | in_progress | done | closed */
            status?: string | null;
            title?: string | null;
        };
        /** @description 프로필의 MCP 연결 */
        McpLink: {
            /** @description installed | accessible */
            access_mode: string;
            /** Format: int64 */
            mcp_sn: number;
        };
        /** @description 멤버 (API 응답 형태) */
        Member: {
            color?: string | null;
            create_at: string;
            /** @description orch | task | wait */
            first_task_mode: string;
            icon?: string | null;
            /** Format: int64 */
            is_orch: number;
            name: string;
            /** Format: int64 */
            profile_sn: number;
            role_name: string;
            /** Format: int64 */
            sn: number;
            /** Format: int64 */
            sort: number;
            /** @description running | waiting | idle | paused | archived */
            status: string;
            /** Format: int64 */
            team_sn: number;
            /** Format: int64 */
            template_sn?: number | null;
            /** Format: int64 */
            template_version?: number | null;
            update_at: string;
        };
        /** @description 멤버 추가 요청 본문. template_sn이 있으면 live 버전 프로필을 복사하고 역할 · 아이콘 · 색을 템플릿에서 가져온다 */
        MemberNew: {
            color?: string | null;
            /** @description orch | task | wait, 생략하면 orch */
            first_task_mode?: string | null;
            icon?: string | null;
            name: string;
            /** @description 템플릿 없이 만들 때 필수 (있으면 템플릿 값을 덮어쓴다) */
            role_name?: string | null;
            /** Format: int64 */
            template_sn?: number | null;
        };
        /** @description 멤버 수정 요청 본문. 보낸 필드만 바꾼다 */
        MemberPatch: {
            color?: string | null;
            first_task_mode?: string | null;
            icon?: string | null;
            name?: string | null;
            role_name?: string | null;
            /** Format: int64 */
            sort?: number | null;
            /** @description running | waiting | idle | paused | archived */
            status?: string | null;
        };
        /** @description MoveTask 요청 본문 */
        MoveBody: {
            /** @description 옮겨갈 상태 */
            status: string;
        };
        /** @description 에이전트 프로필 (API 응답 형태) */
        Profile: {
            /** Format: int64 */
            auto_retry_max: number;
            /** Format: int64 */
            connection_sn?: number | null;
            /** Format: int64 */
            context_warn_percent: number;
            create_at: string;
            /** @description auto | low | medium | high */
            effort: string;
            /** @description bot | personal · null = 워크스페이스 기본 */
            github_mode?: string | null;
            /** @description workspace | template | member */
            kind: string;
            /** Format: int64 */
            model_sn?: number | null;
            /** @description allowlist | open | off */
            network_mode: string;
            /** @description use | ignore */
            repo_rule_mode: string;
            /** Format: int64 */
            run_time_limit_min?: number | null;
            /** Format: int64 */
            run_token_limit?: number | null;
            /** Format: int64 */
            runtime_sn?: number | null;
            /** @description resume_task | new_run */
            session_mode: string;
            /** Format: int64 */
            sn: number;
            /**
             * Format: int64
             * @description 1(읽기 전용) ~ 4(자율)
             */
            trust_level: number;
            update_at: string;
            /** Format: int64 */
            wid: number;
            workdir?: string | null;
        };
        /** @description 생성 요청 본문. 설정값은 DB 기본값으로 시작하고 PATCH로 바꾼다 */
        ProfileNew: {
            /** @description workspace | template | member, 생략하면 workspace */
            kind?: string | null;
        };
        /** @description 수정 요청 본문. 보낸 필드만 바꾼다 (이벤트 payload로도 그대로 저장된다) */
        ProfilePatch: {
            /** Format: int64 */
            auto_retry_max?: number | null;
            /** Format: int64 */
            connection_sn?: number | null;
            /** Format: int64 */
            context_warn_percent?: number | null;
            effort?: string | null;
            github_mode?: string | null;
            /** Format: int64 */
            model_sn?: number | null;
            network_mode?: string | null;
            repo_rule_mode?: string | null;
            /** Format: int64 */
            run_time_limit_min?: number | null;
            /** Format: int64 */
            run_token_limit?: number | null;
            /** Format: int64 */
            runtime_sn?: number | null;
            session_mode?: string | null;
            /**
             * Format: int64
             * @description 1 ~ 4
             */
            trust_level?: number | null;
            workdir?: string | null;
        };
        /** @description 프로젝트 (API 응답 형태) */
        Project: {
            create_at: string;
            default_branch: string;
            import_label?: string | null;
            /** Format: int64 */
            is_github_import: number;
            name: string;
            /** Format: int64 */
            next_num: number;
            repo_name?: string | null;
            repo_path?: string | null;
            /** Format: int64 */
            sn: number;
            /** Format: int64 */
            sort: number;
            /** @description active(진행 중) | archived(보관 · 읽기 전용) */
            status: string;
            /** Format: int64 */
            team_sn?: number | null;
            update_at: string;
            /** Format: int64 */
            wid: number;
        };
        /** @description 생성 요청 본문. name만 필수 (워크스페이스는 Alpha에서 1개 고정), 나머지는 생략하면 DB 기본값을 쓴다 */
        ProjectNew: {
            default_branch?: string | null;
            name: string;
            repo_name?: string | null;
            repo_path?: string | null;
            /** Format: int64 */
            team_sn?: number | null;
        };
        /** @description 수정 요청 본문. 보낸 필드만 바꾼다 (생략 = 그대로 둠) */
        ProjectPatch: {
            default_branch?: string | null;
            name?: string | null;
            repo_name?: string | null;
            repo_path?: string | null;
            /** Format: int64 */
            sort?: number | null;
            status?: string | null;
        };
        /** @description 반려 요청 본문 */
        RejectBody: {
            /**
             * Format: int64
             * @description 리뷰한 멤버 (tbl_review.member_sn이 필수라 받는다)
             */
            member_sn: number;
            /** @description 반려 사유 */
            reason?: string | null;
        };
        /** @description Run (API 응답 형태) */
        Run: {
            branch?: string | null;
            create_at: string;
            end_at?: string | null;
            fail_code?: string | null;
            fail_detail?: string | null;
            /** Format: int64 */
            member_sn: number;
            /**
             * Format: int64
             * @description 화면 표시 번호 (프로젝트 안에서 1부터)
             */
            num: number;
            /** Format: int64 */
            project_sn: number;
            result_summary?: string | null;
            /**
             * Format: int64
             * @description 재시도 대상인 이전 Run
             */
            retry_run_sn?: number | null;
            /** Format: int64 */
            sn: number;
            start_at?: string | null;
            /** @description orch | user | retry */
            start_by: string;
            /** @description queued | starting | running | waiting | review | completed | failed | cancelled */
            status: string;
            /** Format: int64 */
            task_sn: number;
        };
        /** @description Session (API 응답 형태) */
        Session: {
            end_at?: string | null;
            /** Format: int64 */
            is_resumed: number;
            /** Format: int64 */
            member_sn: number;
            /**
             * Format: int64
             * @description 멤버별 표시 번호
             */
            num: number;
            provider_session_id?: string | null;
            rotate_reason?: string | null;
            /** Format: int64 */
            run_sn: number;
            /** Format: int64 */
            sn: number;
            start_at: string;
            /** @description starting | active | stopped | failed */
            status: string;
        };
        /** @description 프로필의 스킬 연결 */
        SkillLink: {
            /** Format: int64 */
            is_enabled: number;
            /** Format: int64 */
            skill_sn: number;
        };
        /** @description 태스크 (API 응답 형태) */
        Task: {
            assign_by?: string | null;
            block_reason?: string | null;
            branch?: string | null;
            /** Format: int64 */
            commit_count: number;
            create_at: string;
            create_by: string;
            description?: string | null;
            done_at?: string | null;
            /** Format: int64 */
            estimate_min?: number | null;
            eta_at?: string | null;
            /** Format: int64 */
            issue_sn?: number | null;
            /** Format: int64 */
            member_sn?: number | null;
            /**
             * Format: int64
             * @description 화면 표시 번호 (이슈와 공용)
             */
            num: number;
            /** Format: int64 */
            pr_number?: number | null;
            pr_status?: string | null;
            /**
             * Format: int64
             * @description 0(P0) ~ 3(P3)
             */
            priority: number;
            /** Format: int64 */
            project_sn: number;
            /** Format: int64 */
            queue_sort?: number | null;
            /** Format: int64 */
            sn: number;
            start_at?: string | null;
            /** @description backlog | todo | in_progress | blocked | review | done | failed | cancelled */
            status: string;
            title: string;
            update_at: string;
        };
        /** @description 생성 요청 본문. 상태는 항상 todo로 시작한다 */
        TaskNew: {
            description?: string | null;
            /**
             * Format: int64
             * @description 0(P0) ~ 3(P3), 생략하면 2
             */
            priority?: number | null;
            title: string;
        };
        /** @description 수정 요청 본문. 보낸 필드만 바꾼다 (이벤트 payload로도 그대로 저장된다). 상태는 `/tasks/{sn}/move`로만 바꾼다 */
        TaskPatch: {
            description?: string | null;
            /**
             * Format: int64
             * @description 0(P0) ~ 3(P3)
             */
            priority?: number | null;
            /** Format: int64 */
            queue_sort?: number | null;
            title?: string | null;
        };
        /** @description 팀 (API 응답 형태) */
        Team: {
            /** Format: int64 */
            context_warn_percent: number;
            create_at: string;
            /** Format: int64 */
            daily_token_budget?: number | null;
            /** Format: int64 */
            is_review_required: number;
            /** @description orch | project */
            kind: string;
            /** Format: int64 */
            max_concurrent_run: number;
            name: string;
            /** @description read | branch | push */
            repo_permission: string;
            repo_scope?: string | null;
            /** @description before_merge | before_done */
            review_stage: string;
            /** Format: int64 */
            sn: number;
            /** Format: int64 */
            sort: number;
            update_at: string;
        };
        /** @description 팀 생성 요청 본문. 나머지 설정은 DB 기본값으로 시작한다 */
        TeamNew: {
            /** @description orch | project, 생략하면 project */
            kind?: string | null;
            name: string;
        };
        /** @description 팀 수정 요청 본문. 보낸 필드만 바꾼다 */
        TeamPatch: {
            /** Format: int64 */
            context_warn_percent?: number | null;
            /** Format: int64 */
            daily_token_budget?: number | null;
            /** Format: int64 */
            is_review_required?: number | null;
            /** Format: int64 */
            max_concurrent_run?: number | null;
            name?: string | null;
            repo_permission?: string | null;
            repo_scope?: string | null;
            review_stage?: string | null;
            /** Format: int64 */
            sort?: number | null;
        };
        /** @description 역할 템플릿 (API 응답 형태) */
        Template: {
            /** @description dev | verify | design_pm | orch */
            category: string;
            color?: string | null;
            create_at: string;
            description?: string | null;
            icon?: string | null;
            /** Format: int64 */
            is_orch: number;
            name: string;
            role_name?: string | null;
            /** Format: int64 */
            sn: number;
            /** Format: int64 */
            sort: number;
            /** @description draft | active | archived */
            status: string;
            /** @description 태그 JSON 배열 문자열 */
            tag_json?: string | null;
            update_at: string;
        };
        /** @description 프로필의 도구 정책 */
        ToolRule: {
            /** @description allow | allowlist | approval | block */
            policy: string;
            scope_text?: string | null;
            /** @description read | edit | shell | git_push | web_fetch | git_destructive */
            tool_code: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    read: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 이슈 번호 */
                sn: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Issue"];
                };
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 이슈 번호 */
                sn: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 삭제됨 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 이슈 번호 */
                sn: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IssuePatch"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Issue"];
                };
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 이슈 번호 */
                sn: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"][];
                };
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 이슈 번호 */
                sn: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskNew"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    member: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 멤버 번호 */
                sn: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Member"];
                };
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 멤버 번호 */
                sn: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 삭제됨 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    edit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 멤버 번호 */
                sn: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemberPatch"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Member"];
                };
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    list: {
        parameters: {
            query?: {
                /** @description 이 종류만 */
                kind?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"][];
                };
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileNew"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    read: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 프로필 번호 */
                sn: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 프로필 번호 */
                sn: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 삭제됨 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 프로필 번호 */
                sn: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfilePatch"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    caps: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 프로필 번호 */
                sn: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Caps"];
                };
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"][];
                };
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectNew"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    read: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 프로젝트 번호 */
                sn: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 프로젝트 번호 */
                sn: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 삭제됨 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 프로젝트 번호 */
                sn: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectPatch"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 프로젝트 번호 */
                sn: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Issue"][];
                };
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 프로젝트 번호 */
                sn: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IssueNew"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Issue"];
                };
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    board: {
        parameters: {
            query?: {
                /** @description 이 상태만 */
                status?: string;
            };
            header?: never;
            path: {
                /** @description 프로젝트 번호 */
                sn: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"][];
                };
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    read: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Run 번호 */
                sn: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    approve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Run 번호 */
                sn: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    reject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Run 번호 */
                sn: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RejectBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    retry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 재시도할 Run 번호 */
                sn: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    review: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Run 번호 */
                sn: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    sessions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Run 번호 */
                sn: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"][];
                };
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    stop: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Run 번호 */
                sn: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    read: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 태스크 번호 */
                sn: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 태스크 번호 */
                sn: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 삭제됨 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 태스크 번호 */
                sn: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskPatch"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    assign: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 태스크 번호 */
                sn: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    unassign: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 태스크 번호 */
                sn: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    mv: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 태스크 번호 */
                sn: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MoveBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 태스크 번호 */
                sn: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"][];
                };
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    start: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 태스크 번호 */
                sn: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Team"][];
                };
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TeamNew"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Team"];
                };
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    read: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 팀 번호 */
                sn: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Team"];
                };
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 팀 번호 */
                sn: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 삭제됨 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 팀 번호 */
                sn: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TeamPatch"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Team"];
                };
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    members: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 팀 번호 */
                sn: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Member"][];
                };
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    add: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 팀 번호 */
                sn: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemberNew"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Member"];
                };
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    templates: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Template"][];
                };
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    template: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 템플릿 번호 */
                sn: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Template"];
                };
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
}
