//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, serde :: Serialize)]
#[sea_orm(table_name = "tbl_map_profile_skill")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub sn: i64,
    pub profile_sn: i64,
    pub skill_sn: i64,
    pub is_enabled: i64,
    #[sea_orm(column_type = "Text")]
    pub create_at: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::tbl_agent_profile::Entity",
        from = "Column::ProfileSn",
        to = "super::tbl_agent_profile::Column::Sn",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    TblAgentProfile,
    #[sea_orm(
        belongs_to = "super::tbl_skill::Entity",
        from = "Column::SkillSn",
        to = "super::tbl_skill::Column::Sn",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    TblSkill,
}

impl Related<super::tbl_agent_profile::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblAgentProfile.def()
    }
}

impl Related<super::tbl_skill::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblSkill.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
