//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, serde :: Serialize)]
#[sea_orm(table_name = "tbl_log_token")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub sn: i64,
    pub run_sn: i64,
    pub session_sn: Option<i64>,
    pub connection_sn: Option<i64>,
    pub manifest_sn: Option<i64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub model_code: Option<String>,
    pub token_input: i64,
    pub token_cache_read: i64,
    pub token_cache_write: i64,
    pub token_output: i64,
    pub context_token: Option<i64>,
    pub cost_usd_micro: i64,
    #[sea_orm(column_type = "Text")]
    pub usage_source: String,
    #[sea_orm(column_type = "Text")]
    pub create_at: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::tbl_connection::Entity",
        from = "Column::ConnectionSn",
        to = "super::tbl_connection::Column::Sn",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    TblConnection,
    #[sea_orm(
        belongs_to = "super::tbl_context_manifest::Entity",
        from = "Column::ManifestSn",
        to = "super::tbl_context_manifest::Column::Sn",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    TblContextManifest,
    #[sea_orm(
        belongs_to = "super::tbl_run::Entity",
        from = "Column::RunSn",
        to = "super::tbl_run::Column::Sn",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    TblRun,
    #[sea_orm(
        belongs_to = "super::tbl_session::Entity",
        from = "Column::SessionSn",
        to = "super::tbl_session::Column::Sn",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    TblSession,
}

impl Related<super::tbl_connection::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblConnection.def()
    }
}

impl Related<super::tbl_context_manifest::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblContextManifest.def()
    }
}

impl Related<super::tbl_run::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblRun.def()
    }
}

impl Related<super::tbl_session::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblSession.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
