//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, serde :: Serialize)]
#[sea_orm(table_name = "tbl_skill")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub sn: i64,
    pub wid: i64,
    pub source_sn: Option<i64>,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub version: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub latest_version: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub sha256: Option<String>,
    pub token_cost: i64,
    #[sea_orm(column_type = "Text")]
    pub scan_status: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub scan_message: Option<String>,
    pub is_enabled: i64,
    pub is_blocked: i64,
    #[sea_orm(column_type = "Text")]
    pub install_at: String,
    #[sea_orm(column_type = "Text")]
    pub update_at: String,
    #[sea_orm(column_type = "Text")]
    pub create_at: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::tbl_map_profile_skill::Entity")]
    TblMapProfileSkill,
    #[sea_orm(
        belongs_to = "super::tbl_skill_source::Entity",
        from = "Column::SourceSn",
        to = "super::tbl_skill_source::Column::Sn",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    TblSkillSource,
    #[sea_orm(
        belongs_to = "super::tbl_workspace::Entity",
        from = "Column::Wid",
        to = "super::tbl_workspace::Column::Sn",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    TblWorkspace,
}

impl Related<super::tbl_map_profile_skill::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblMapProfileSkill.def()
    }
}

impl Related<super::tbl_skill_source::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblSkillSource.def()
    }
}

impl Related<super::tbl_workspace::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblWorkspace.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
