//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, serde :: Serialize)]
#[sea_orm(table_name = "tbl_decision_option")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub sn: i64,
    pub question_sn: i64,
    pub sort: i64,
    #[sea_orm(column_type = "Text")]
    pub code: String,
    #[sea_orm(column_type = "Text")]
    pub label: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub note: Option<String>,
    pub is_recommended: i64,
    pub is_selected: i64,
    #[sea_orm(column_type = "Text")]
    pub create_at: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::tbl_decision_question::Entity",
        from = "Column::QuestionSn",
        to = "super::tbl_decision_question::Column::Sn",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    TblDecisionQuestion,
}

impl Related<super::tbl_decision_question::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblDecisionQuestion.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
