//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, serde :: Serialize)]
#[sea_orm(table_name = "tbl_template")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub sn: i64,
    pub wid: i64,
    pub uid: Option<i64>,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub role_name: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub category: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub icon: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub color: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub tag_json: Option<String>,
    pub is_orch: i64,
    #[sea_orm(column_type = "Text")]
    pub status: String,
    pub sort: i64,
    #[sea_orm(column_type = "Text")]
    pub create_at: String,
    #[sea_orm(column_type = "Text")]
    pub update_at: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::tbl_member::Entity")]
    TblMember,
    #[sea_orm(has_many = "super::tbl_template_revision::Entity")]
    TblTemplateRevision,
    #[sea_orm(
        belongs_to = "super::tbl_user::Entity",
        from = "Column::Uid",
        to = "super::tbl_user::Column::Uid",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    TblUser,
    #[sea_orm(
        belongs_to = "super::tbl_workspace::Entity",
        from = "Column::Wid",
        to = "super::tbl_workspace::Column::Sn",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    TblWorkspace,
}

impl Related<super::tbl_member::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblMember.def()
    }
}

impl Related<super::tbl_template_revision::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblTemplateRevision.def()
    }
}

impl Related<super::tbl_user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblUser.def()
    }
}

impl Related<super::tbl_workspace::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblWorkspace.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
