//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, serde :: Serialize)]
#[sea_orm(table_name = "tbl_contract")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub sn: i64,
    pub project_sn: i64,
    #[sea_orm(column_type = "Text")]
    pub kind: String,
    #[sea_orm(column_type = "Text")]
    pub contract_key: String,
    pub version: i64,
    #[sea_orm(column_type = "Text")]
    pub summary: String,
    pub owner_task_sn: Option<i64>,
    pub update_run_sn: Option<i64>,
    #[sea_orm(column_type = "Text")]
    pub update_at: String,
    #[sea_orm(column_type = "Text")]
    pub create_at: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::tbl_log_contract::Entity")]
    TblLogContract,
    #[sea_orm(has_many = "super::tbl_map_task_contract::Entity")]
    TblMapTaskContract,
    #[sea_orm(
        belongs_to = "super::tbl_project::Entity",
        from = "Column::ProjectSn",
        to = "super::tbl_project::Column::Sn",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    TblProject,
    #[sea_orm(has_many = "super::tbl_report_item::Entity")]
    TblReportItem,
    #[sea_orm(
        belongs_to = "super::tbl_run::Entity",
        from = "Column::UpdateRunSn",
        to = "super::tbl_run::Column::Sn",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    TblRun,
    #[sea_orm(
        belongs_to = "super::tbl_task::Entity",
        from = "Column::OwnerTaskSn",
        to = "super::tbl_task::Column::Sn",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    TblTask,
}

impl Related<super::tbl_log_contract::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblLogContract.def()
    }
}

impl Related<super::tbl_map_task_contract::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblMapTaskContract.def()
    }
}

impl Related<super::tbl_project::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblProject.def()
    }
}

impl Related<super::tbl_report_item::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblReportItem.def()
    }
}

impl Related<super::tbl_run::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblRun.def()
    }
}

impl Related<super::tbl_task::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblTask.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
