//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, serde :: Serialize)]
#[sea_orm(table_name = "tbl_user")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub sn: i64,
    #[sea_orm(column_type = "Text", nullable, unique)]
    pub email: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub password_hash: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub initial: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub ui_language: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub status: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub last_login_at: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub create_at: String,
    #[sea_orm(column_type = "Text")]
    pub update_at: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::tbl_approval::Entity")]
    TblApproval,
    #[sea_orm(has_many = "super::tbl_attachment::Entity")]
    TblAttachment,
    #[sea_orm(has_many = "super::tbl_connection::Entity")]
    TblConnection,
    #[sea_orm(has_many = "super::tbl_conversation::Entity")]
    TblConversation,
    #[sea_orm(has_many = "super::tbl_decision::Entity")]
    TblDecision,
    #[sea_orm(has_many = "super::tbl_diagram_node::Entity")]
    TblDiagramNode,
    #[sea_orm(has_many = "super::tbl_diagram_view::Entity")]
    TblDiagramView,
    #[sea_orm(has_many = "super::tbl_instruction_preset::Entity")]
    TblInstructionPreset,
    #[sea_orm(has_many = "super::tbl_instruction_preset_version::Entity")]
    TblInstructionPresetVersion,
    #[sea_orm(has_many = "super::tbl_interaction::Entity")]
    TblInteraction,
    #[sea_orm(has_many = "super::tbl_issue::Entity")]
    TblIssue,
    #[sea_orm(has_many = "super::tbl_log_activity::Entity")]
    TblLogActivity,
    #[sea_orm(has_many = "super::tbl_log_audit::Entity")]
    TblLogAudit,
    #[sea_orm(has_many = "super::tbl_log_event::Entity")]
    TblLogEvent,
    #[sea_orm(has_many = "super::tbl_notification::Entity")]
    TblNotification,
    #[sea_orm(has_many = "super::tbl_orch_proposal::Entity")]
    TblOrchProposal,
    #[sea_orm(has_many = "super::tbl_task::Entity")]
    TblTask,
    #[sea_orm(has_many = "super::tbl_task_view::Entity")]
    TblTaskView,
    #[sea_orm(has_many = "super::tbl_template::Entity")]
    TblTemplate,
    #[sea_orm(has_many = "super::tbl_template_revision::Entity")]
    TblTemplateRevision,
    #[sea_orm(has_many = "super::tbl_workspace::Entity")]
    TblWorkspace,
}

impl Related<super::tbl_approval::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblApproval.def()
    }
}

impl Related<super::tbl_attachment::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblAttachment.def()
    }
}

impl Related<super::tbl_connection::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblConnection.def()
    }
}

impl Related<super::tbl_conversation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblConversation.def()
    }
}

impl Related<super::tbl_decision::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblDecision.def()
    }
}

impl Related<super::tbl_diagram_node::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblDiagramNode.def()
    }
}

impl Related<super::tbl_diagram_view::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblDiagramView.def()
    }
}

impl Related<super::tbl_instruction_preset::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblInstructionPreset.def()
    }
}

impl Related<super::tbl_instruction_preset_version::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblInstructionPresetVersion.def()
    }
}

impl Related<super::tbl_interaction::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblInteraction.def()
    }
}

impl Related<super::tbl_issue::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblIssue.def()
    }
}

impl Related<super::tbl_log_activity::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblLogActivity.def()
    }
}

impl Related<super::tbl_log_audit::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblLogAudit.def()
    }
}

impl Related<super::tbl_log_event::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblLogEvent.def()
    }
}

impl Related<super::tbl_notification::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblNotification.def()
    }
}

impl Related<super::tbl_orch_proposal::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblOrchProposal.def()
    }
}

impl Related<super::tbl_task::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblTask.def()
    }
}

impl Related<super::tbl_task_view::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblTaskView.def()
    }
}

impl Related<super::tbl_template::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblTemplate.def()
    }
}

impl Related<super::tbl_template_revision::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblTemplateRevision.def()
    }
}

impl Related<super::tbl_workspace::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblWorkspace.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
