//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, serde :: Serialize)]
#[sea_orm(table_name = "tbl_runtime")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub sn: i64,
    pub workspace_sn: i64,
    #[sea_orm(column_type = "Text")]
    pub code: String,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub version: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub latest_version: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub bin_path: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub install_status: String,
    #[sea_orm(column_type = "Text")]
    pub login_status: String,
    pub sort: i64,
    #[sea_orm(column_type = "Text", nullable)]
    pub detect_at: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub create_at: String,
    #[sea_orm(column_type = "Text")]
    pub update_at: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::tbl_agent_profile::Entity")]
    TblAgentProfile,
    #[sea_orm(has_many = "super::tbl_connection::Entity")]
    TblConnection,
    #[sea_orm(has_many = "super::tbl_map_fallback::Entity")]
    TblMapFallback,
    #[sea_orm(has_many = "super::tbl_map_runtime_connection::Entity")]
    TblMapRuntimeConnection,
    #[sea_orm(has_many = "super::tbl_run::Entity")]
    TblRun,
    #[sea_orm(
        belongs_to = "super::tbl_workspace::Entity",
        from = "Column::WorkspaceSn",
        to = "super::tbl_workspace::Column::Sn",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    TblWorkspace,
}

impl Related<super::tbl_agent_profile::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblAgentProfile.def()
    }
}

impl Related<super::tbl_connection::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblConnection.def()
    }
}

impl Related<super::tbl_map_fallback::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblMapFallback.def()
    }
}

impl Related<super::tbl_map_runtime_connection::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblMapRuntimeConnection.def()
    }
}

impl Related<super::tbl_run::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblRun.def()
    }
}

impl Related<super::tbl_workspace::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblWorkspace.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
