//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, serde :: Serialize)]
#[sea_orm(table_name = "tbl_connection")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub sn: i64,
    pub workspace_sn: i64,
    pub user_sn: Option<i64>,
    #[sea_orm(column_type = "Text")]
    pub kind: String,
    #[sea_orm(column_type = "Text")]
    pub provider_code: String,
    #[sea_orm(column_type = "Text")]
    pub provider_name: String,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub account_label: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub plan_name: Option<String>,
    pub runtime_sn: Option<i64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub login_method: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub base_url: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub key_ref: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub key_hint: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub status: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub status_message: Option<String>,
    pub monthly_budget_usd_micro: Option<i64>,
    pub monthly_fee_usd_micro: Option<i64>,
    pub budget_warn_percent: i64,
    pub is_budget_exclude: i64,
    #[sea_orm(column_type = "Text")]
    pub scope: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub report_language: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub commit_language: Option<String>,
    pub latency_ms: Option<i64>,
    pub cache_hit_percent: Option<i64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub test_at: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub sync_at: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub create_at: String,
    #[sea_orm(column_type = "Text")]
    pub update_at: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::tbl_agent_profile::Entity")]
    TblAgentProfile,
    #[sea_orm(has_many = "super::tbl_connection_quota::Entity")]
    TblConnectionQuota,
    #[sea_orm(has_many = "super::tbl_log_connection_quota::Entity")]
    TblLogConnectionQuota,
    #[sea_orm(has_many = "super::tbl_log_token::Entity")]
    TblLogToken,
    #[sea_orm(has_many = "super::tbl_map_connection_team::Entity")]
    TblMapConnectionTeam,
    #[sea_orm(has_many = "super::tbl_map_fallback::Entity")]
    TblMapFallback,
    #[sea_orm(has_many = "super::tbl_map_runtime_connection::Entity")]
    TblMapRuntimeConnection,
    #[sea_orm(has_many = "super::tbl_model::Entity")]
    TblModel,
    #[sea_orm(has_many = "super::tbl_notify_rule::Entity")]
    TblNotifyRule,
    #[sea_orm(has_many = "super::tbl_run::Entity")]
    TblRun,
    #[sea_orm(
        belongs_to = "super::tbl_runtime::Entity",
        from = "Column::RuntimeSn",
        to = "super::tbl_runtime::Column::Sn",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    TblRuntime,
    #[sea_orm(
        belongs_to = "super::tbl_user::Entity",
        from = "Column::UserSn",
        to = "super::tbl_user::Column::Sn",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    TblUser,
    #[sea_orm(
        belongs_to = "super::tbl_workspace::Entity",
        from = "Column::WorkspaceSn",
        to = "super::tbl_workspace::Column::Sn",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    TblWorkspace,
}

impl Related<super::tbl_agent_profile::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblAgentProfile.def()
    }
}

impl Related<super::tbl_connection_quota::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblConnectionQuota.def()
    }
}

impl Related<super::tbl_log_connection_quota::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblLogConnectionQuota.def()
    }
}

impl Related<super::tbl_log_token::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblLogToken.def()
    }
}

impl Related<super::tbl_map_connection_team::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblMapConnectionTeam.def()
    }
}

impl Related<super::tbl_map_fallback::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblMapFallback.def()
    }
}

impl Related<super::tbl_map_runtime_connection::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblMapRuntimeConnection.def()
    }
}

impl Related<super::tbl_model::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblModel.def()
    }
}

impl Related<super::tbl_notify_rule::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblNotifyRule.def()
    }
}

impl Related<super::tbl_run::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblRun.def()
    }
}

impl Related<super::tbl_runtime::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblRuntime.def()
    }
}

impl Related<super::tbl_user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblUser.def()
    }
}

impl Related<super::tbl_workspace::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblWorkspace.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
