//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, serde :: Serialize)]
#[sea_orm(table_name = "tbl_map_task_contract")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub sn: i64,
    pub task_sn: i64,
    pub contract_sn: i64,
    #[sea_orm(column_type = "Text")]
    pub role: String,
    pub seen_version: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::tbl_contract::Entity",
        from = "Column::ContractSn",
        to = "super::tbl_contract::Column::Sn",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    TblContract,
    #[sea_orm(
        belongs_to = "super::tbl_task::Entity",
        from = "Column::TaskSn",
        to = "super::tbl_task::Column::Sn",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    TblTask,
}

impl Related<super::tbl_contract::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblContract.def()
    }
}

impl Related<super::tbl_task::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblTask.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
