//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, serde :: Serialize)]
#[sea_orm(table_name = "tbl_run")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub sn: i64,
    pub project_sn: i64,
    pub task_sn: i64,
    pub member_sn: i64,
    pub num: i64,
    #[sea_orm(column_type = "Text")]
    pub status: String,
    #[sea_orm(column_type = "Text")]
    pub start_by: String,
    pub retry_run_sn: Option<i64>,
    #[sea_orm(unique_key = "ux_run_child")]
    pub parent_run_sn: Option<i64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub spawn_mode: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub tier: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub brief: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub kind: Option<String>,
    #[sea_orm(unique_key = "ux_run_child")]
    pub child_seq: Option<i64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub paths: Option<String>,
    pub wait_run_sn: Option<i64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub wait_glob: Option<String>,
    pub runtime_sn: Option<i64>,
    pub connection_sn: Option<i64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub model_code: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub effort: Option<String>,
    pub is_fallback: i64,
    #[sea_orm(column_type = "Text", nullable)]
    pub result_summary: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub fail_code: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub fail_detail: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub branch: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub workdir: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub workdir_clean_at: Option<String>,
    pub token_input: Option<i64>,
    pub token_cache_read: Option<i64>,
    pub token_cache_write: Option<i64>,
    pub token_output: Option<i64>,
    pub context_token: Option<i64>,
    pub context_limit: Option<i64>,
    pub cost_usd_micro: Option<i64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub start_at: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub end_at: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub create_at: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::tbl_ask::Entity")]
    TblAsk,
    #[sea_orm(
        belongs_to = "super::tbl_connection::Entity",
        from = "Column::ConnectionSn",
        to = "super::tbl_connection::Column::Sn",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    TblConnection,
    #[sea_orm(has_many = "super::tbl_context_manifest::Entity")]
    TblContextManifest,
    #[sea_orm(has_many = "super::tbl_contract::Entity")]
    TblContract,
    #[sea_orm(has_many = "super::tbl_log_activity::Entity")]
    TblLogActivity,
    #[sea_orm(has_many = "super::tbl_log_audit::Entity")]
    TblLogAudit,
    #[sea_orm(has_many = "super::tbl_log_contract::Entity")]
    TblLogContract,
    #[sea_orm(has_many = "super::tbl_log_event::Entity")]
    TblLogEvent,
    #[sea_orm(has_many = "super::tbl_log_run::Entity")]
    TblLogRun,
    #[sea_orm(has_many = "super::tbl_log_token::Entity")]
    TblLogToken,
    #[sea_orm(
        belongs_to = "super::tbl_member::Entity",
        from = "Column::MemberSn",
        to = "super::tbl_member::Column::Sn",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    TblMember,
    #[sea_orm(has_many = "super::tbl_message::Entity")]
    TblMessage,
    #[sea_orm(
        belongs_to = "super::tbl_project::Entity",
        from = "Column::ProjectSn",
        to = "super::tbl_project::Column::Sn",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    TblProject,
    #[sea_orm(has_many = "super::tbl_report_item::Entity")]
    TblReportItem,
    #[sea_orm(has_many = "super::tbl_review::Entity")]
    TblReview,
    #[sea_orm(
        belongs_to = "Entity",
        from = "Column::WaitRunSn",
        to = "Column::Sn",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    SelfRef3,
    #[sea_orm(
        belongs_to = "Entity",
        from = "Column::ParentRunSn",
        to = "Column::Sn",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    SelfRef2,
    #[sea_orm(
        belongs_to = "Entity",
        from = "Column::RetryRunSn",
        to = "Column::Sn",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    SelfRef1,
    #[sea_orm(has_many = "super::tbl_run_file::Entity")]
    TblRunFile,
    #[sea_orm(
        belongs_to = "super::tbl_runtime::Entity",
        from = "Column::RuntimeSn",
        to = "super::tbl_runtime::Column::Sn",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    TblRuntime,
    #[sea_orm(has_many = "super::tbl_session::Entity")]
    TblSession,
    #[sea_orm(
        belongs_to = "super::tbl_task::Entity",
        from = "Column::TaskSn",
        to = "super::tbl_task::Column::Sn",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    TblTask,
}

impl Related<super::tbl_ask::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblAsk.def()
    }
}

impl Related<super::tbl_connection::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblConnection.def()
    }
}

impl Related<super::tbl_context_manifest::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblContextManifest.def()
    }
}

impl Related<super::tbl_contract::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblContract.def()
    }
}

impl Related<super::tbl_log_activity::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblLogActivity.def()
    }
}

impl Related<super::tbl_log_audit::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblLogAudit.def()
    }
}

impl Related<super::tbl_log_contract::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblLogContract.def()
    }
}

impl Related<super::tbl_log_event::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblLogEvent.def()
    }
}

impl Related<super::tbl_log_run::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblLogRun.def()
    }
}

impl Related<super::tbl_log_token::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblLogToken.def()
    }
}

impl Related<super::tbl_member::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblMember.def()
    }
}

impl Related<super::tbl_message::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblMessage.def()
    }
}

impl Related<super::tbl_project::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblProject.def()
    }
}

impl Related<super::tbl_report_item::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblReportItem.def()
    }
}

impl Related<super::tbl_review::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblReview.def()
    }
}

impl Related<super::tbl_run_file::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblRunFile.def()
    }
}

impl Related<super::tbl_runtime::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblRuntime.def()
    }
}

impl Related<super::tbl_session::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblSession.def()
    }
}

impl Related<super::tbl_task::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblTask.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
