//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, serde :: Serialize)]
#[sea_orm(table_name = "tbl_orch_policy_level")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub sn: i64,
    pub policy_sn: i64,
    pub level: i64,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub example: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub handle: String,
    pub wait_min: Option<i64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub no_reply: Option<String>,
    pub is_locked: i64,
    #[sea_orm(column_type = "Text")]
    pub create_at: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::tbl_orch_policy::Entity",
        from = "Column::PolicySn",
        to = "super::tbl_orch_policy::Column::Sn",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    TblOrchPolicy,
}

impl Related<super::tbl_orch_policy::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblOrchPolicy.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
