//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, serde :: Serialize)]
#[sea_orm(table_name = "tbl_notify_rule")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub sn: i64,
    #[sea_orm(unique_key = "ux_notify_rule")]
    pub workspace_sn: i64,
    pub connection_sn: Option<i64>,
    #[sea_orm(column_type = "Text", unique_key = "ux_notify_rule")]
    pub event_code: String,
    #[sea_orm(column_type = "Text", unique_key = "ux_notify_rule")]
    pub channel_kind: String,
    pub is_enabled: i64,
    #[sea_orm(column_type = "Text")]
    pub update_at: String,
    #[sea_orm(column_type = "Text")]
    pub create_at: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::tbl_connection::Entity",
        from = "Column::ConnectionSn",
        to = "super::tbl_connection::Column::Sn",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    TblConnection,
    #[sea_orm(
        belongs_to = "super::tbl_workspace::Entity",
        from = "Column::WorkspaceSn",
        to = "super::tbl_workspace::Column::Sn",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    TblWorkspace,
}

impl Related<super::tbl_connection::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblConnection.def()
    }
}

impl Related<super::tbl_workspace::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblWorkspace.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
