//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, serde :: Serialize)]
#[sea_orm(table_name = "tbl_profile_rule")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub sn: i64,
    pub profile_sn: i64,
    #[sea_orm(column_type = "Text")]
    pub action_code: String,
    #[sea_orm(column_type = "Text")]
    pub title: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub pattern: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub policy: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub approver: Option<String>,
    pub is_notify: i64,
    pub sort: i64,
    #[sea_orm(column_type = "Text")]
    pub create_at: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::tbl_agent_profile::Entity",
        from = "Column::ProfileSn",
        to = "super::tbl_agent_profile::Column::Sn",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    TblAgentProfile,
}

impl Related<super::tbl_agent_profile::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblAgentProfile.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
