//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, serde :: Serialize)]
#[sea_orm(table_name = "tbl_decision_question")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub sn: i64,
    pub decision_sn: i64,
    pub sort: i64,
    #[sea_orm(column_type = "Text")]
    pub title: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub body: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub code_snippet: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub ref_json: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub answer_text: Option<String>,
    pub is_delegate: i64,
    #[sea_orm(column_type = "Text", nullable)]
    pub answer_at: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub create_at: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::tbl_decision::Entity",
        from = "Column::DecisionSn",
        to = "super::tbl_decision::Column::Sn",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    TblDecision,
    #[sea_orm(has_many = "super::tbl_decision_option::Entity")]
    TblDecisionOption,
}

impl Related<super::tbl_decision::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblDecision.def()
    }
}

impl Related<super::tbl_decision_option::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblDecisionOption.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
