//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, serde :: Serialize)]
#[sea_orm(table_name = "tbl_log_run")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub sn: i64,
    pub run_sn: i64,
    pub session_sn: Option<i64>,
    #[sea_orm(column_type = "Text")]
    pub kind: String,
    #[sea_orm(column_type = "Text")]
    pub level: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub title: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub message: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub create_at: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::tbl_run::Entity",
        from = "Column::RunSn",
        to = "super::tbl_run::Column::Sn",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    TblRun,
    #[sea_orm(
        belongs_to = "super::tbl_session::Entity",
        from = "Column::SessionSn",
        to = "super::tbl_session::Column::Sn",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    TblSession,
}

impl Related<super::tbl_run::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblRun.def()
    }
}

impl Related<super::tbl_session::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblSession.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
