//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, serde :: Serialize)]
#[sea_orm(table_name = "tbl_map_task_dependency")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub sn: i64,
    pub task_sn: i64,
    pub depend_task_sn: i64,
    #[sea_orm(column_type = "Text")]
    pub create_at: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::tbl_task::Entity",
        from = "Column::DependTaskSn",
        to = "super::tbl_task::Column::Sn",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    TblTask2,
    #[sea_orm(
        belongs_to = "super::tbl_task::Entity",
        from = "Column::TaskSn",
        to = "super::tbl_task::Column::Sn",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    TblTask1,
}

impl ActiveModelBehavior for ActiveModel {}
