//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, serde :: Serialize)]
#[sea_orm(table_name = "tbl_map_profile_mcp")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub sn: i64,
    pub profile_sn: i64,
    pub mcp_sn: i64,
    #[sea_orm(column_type = "Text")]
    pub access_mode: String,
    #[sea_orm(column_type = "Text")]
    pub create_at: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::tbl_agent_profile::Entity",
        from = "Column::ProfileSn",
        to = "super::tbl_agent_profile::Column::Sn",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    TblAgentProfile,
    #[sea_orm(
        belongs_to = "super::tbl_mcp::Entity",
        from = "Column::McpSn",
        to = "super::tbl_mcp::Column::Sn",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    TblMcp,
}

impl Related<super::tbl_agent_profile::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblAgentProfile.def()
    }
}

impl Related<super::tbl_mcp::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblMcp.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
