//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, serde :: Serialize)]
#[sea_orm(table_name = "tbl_model")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub sn: i64,
    pub connection_sn: i64,
    #[sea_orm(column_type = "Text")]
    pub code: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub vendor: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub tag_json: Option<String>,
    pub context_limit: Option<i64>,
    pub context_max: Option<i64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub price_in_usd: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub price_out_usd: Option<f64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub speed: Option<String>,
    pub is_recommended: i64,
    pub is_tested: i64,
    pub is_pinned: i64,
    pub is_visible: i64,
    #[sea_orm(column_type = "Text", nullable)]
    pub sync_at: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub create_at: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::tbl_agent_profile::Entity")]
    TblAgentProfile,
    #[sea_orm(
        belongs_to = "super::tbl_connection::Entity",
        from = "Column::ConnectionSn",
        to = "super::tbl_connection::Column::Sn",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    TblConnection,
}

impl Related<super::tbl_agent_profile::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblAgentProfile.def()
    }
}

impl Related<super::tbl_connection::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblConnection.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
