//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, serde :: Serialize)]
#[sea_orm(table_name = "tbl_orch_guard")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub sn: i64,
    pub policy_sn: i64,
    #[sea_orm(column_type = "Text")]
    pub code: String,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    pub threshold: i64,
    #[sea_orm(column_type = "Text")]
    pub threshold_unit: String,
    #[sea_orm(column_type = "Text")]
    pub scope: String,
    pub sub_threshold: Option<i64>,
    #[sea_orm(column_type = "Text")]
    pub on_trigger: String,
    pub is_enabled: i64,
    #[sea_orm(column_type = "Text", nullable)]
    pub trigger_at: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub create_at: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::tbl_orch_policy::Entity",
        from = "Column::PolicySn",
        to = "super::tbl_orch_policy::Column::Sn",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    TblOrchPolicy,
    #[sea_orm(has_many = "super::tbl_orch_proposal::Entity")]
    TblOrchProposal,
}

impl Related<super::tbl_orch_policy::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblOrchPolicy.def()
    }
}

impl Related<super::tbl_orch_proposal::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblOrchProposal.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
