//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, serde :: Serialize)]
#[sea_orm(table_name = "tbl_team")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub sn: i64,
    pub wid: i64,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub kind: String,
    pub daily_token_budget: Option<i64>,
    pub context_warn_percent: i64,
    pub max_concurrent_run: i64,
    pub spawn_mode: String,
    pub spawn_allow: String,
    pub max_child_run: i64,
    pub is_review_required: i64,
    #[sea_orm(column_type = "Text")]
    pub review_stage: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub repo_scope: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub repo_permission: String,
    pub sort: i64,
    #[sea_orm(column_type = "Text")]
    pub create_at: String,
    #[sea_orm(column_type = "Text")]
    pub update_at: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::tbl_log_activity::Entity")]
    TblLogActivity,
    #[sea_orm(has_many = "super::tbl_map_connection_team::Entity")]
    TblMapConnectionTeam,
    #[sea_orm(has_many = "super::tbl_member::Entity")]
    TblMember,
    #[sea_orm(has_many = "super::tbl_orch_policy::Entity")]
    TblOrchPolicy,
    #[sea_orm(has_many = "super::tbl_project::Entity")]
    TblProject,
    #[sea_orm(
        belongs_to = "super::tbl_workspace::Entity",
        from = "Column::Wid",
        to = "super::tbl_workspace::Column::Sn",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    TblWorkspace,
}

impl Related<super::tbl_log_activity::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblLogActivity.def()
    }
}

impl Related<super::tbl_map_connection_team::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblMapConnectionTeam.def()
    }
}

impl Related<super::tbl_member::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblMember.def()
    }
}

impl Related<super::tbl_orch_policy::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblOrchPolicy.def()
    }
}

impl Related<super::tbl_project::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblProject.def()
    }
}

impl Related<super::tbl_workspace::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblWorkspace.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
