//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, serde :: Serialize)]
#[sea_orm(table_name = "tbl_orch_policy")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub sn: i64,
    #[sea_orm(unique_key = "ux_orch_policy")]
    pub team_sn: i64,
    pub project_sn: Option<i64>,
    #[sea_orm(column_type = "Text")]
    pub mode: String,
    pub timer_sec: i64,
    pub is_pause_on_view: i64,
    #[sea_orm(column_type = "Text")]
    pub create_at: String,
    #[sea_orm(column_type = "Text")]
    pub update_at: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::tbl_orch_guard::Entity")]
    TblOrchGuard,
    #[sea_orm(has_many = "super::tbl_orch_policy_level::Entity")]
    TblOrchPolicyLevel,
    #[sea_orm(
        belongs_to = "super::tbl_project::Entity",
        from = "Column::ProjectSn",
        to = "super::tbl_project::Column::Sn",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    TblProject,
    #[sea_orm(
        belongs_to = "super::tbl_team::Entity",
        from = "Column::TeamSn",
        to = "super::tbl_team::Column::Sn",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    TblTeam,
}

impl Related<super::tbl_orch_guard::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblOrchGuard.def()
    }
}

impl Related<super::tbl_orch_policy_level::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblOrchPolicyLevel.def()
    }
}

impl Related<super::tbl_project::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblProject.def()
    }
}

impl Related<super::tbl_team::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblTeam.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
