//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, serde :: Serialize)]
#[sea_orm(table_name = "tbl_log_connection_quota")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub sn: i64,
    pub connection_sn: i64,
    #[sea_orm(column_type = "Text")]
    pub period: String,
    #[sea_orm(column_type = "Double")]
    pub used_value: f64,
    pub remain_percent: Option<i64>,
    #[sea_orm(column_type = "Text")]
    pub create_at: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::tbl_connection::Entity",
        from = "Column::ConnectionSn",
        to = "super::tbl_connection::Column::Sn",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    TblConnection,
}

impl Related<super::tbl_connection::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblConnection.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
