//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, serde :: Serialize)]
#[sea_orm(table_name = "tbl_notification")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub sn: i64,
    pub wid: i64,
    pub uid: i64,
    #[sea_orm(column_type = "Text")]
    pub event_code: String,
    #[sea_orm(column_type = "Text")]
    pub actor_type: String,
    pub member_sn: Option<i64>,
    #[sea_orm(column_type = "Text")]
    pub title: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub body: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub ref_type: Option<String>,
    pub ref_sn: Option<i64>,
    pub is_action: i64,
    pub is_read: i64,
    pub event_sn: Option<i64>,
    #[sea_orm(column_type = "Text")]
    pub create_at: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub read_at: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::tbl_member::Entity",
        from = "Column::MemberSn",
        to = "super::tbl_member::Column::Sn",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    TblMember,
    #[sea_orm(
        belongs_to = "super::tbl_user::Entity",
        from = "Column::Uid",
        to = "super::tbl_user::Column::Uid",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    TblUser,
    #[sea_orm(
        belongs_to = "super::tbl_workspace::Entity",
        from = "Column::Wid",
        to = "super::tbl_workspace::Column::Sn",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    TblWorkspace,
}

impl Related<super::tbl_member::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblMember.def()
    }
}

impl Related<super::tbl_user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblUser.def()
    }
}

impl Related<super::tbl_workspace::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblWorkspace.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
