//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, serde :: Serialize)]
#[sea_orm(table_name = "tbl_attachment")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub sn: i64,
    #[sea_orm(column_type = "Text")]
    pub owner_type: String,
    pub owner_sn: i64,
    pub uid: Option<i64>,
    #[sea_orm(column_type = "Text")]
    pub file_name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub mime_type: Option<String>,
    pub file_size: i64,
    #[sea_orm(column_type = "Text")]
    pub file_path: String,
    #[sea_orm(column_type = "Text")]
    pub create_at: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::tbl_user::Entity",
        from = "Column::Uid",
        to = "super::tbl_user::Column::Uid",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    TblUser,
}

impl Related<super::tbl_user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblUser.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
