//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, serde :: Serialize)]
#[sea_orm(table_name = "tbl_instruction_preset_version")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub sn: i64,
    pub preset_sn: i64,
    pub version: i64,
    #[sea_orm(column_type = "Text")]
    pub content: String,
    pub token_count: i64,
    #[sea_orm(column_type = "Text")]
    pub language: String,
    #[sea_orm(column_type = "Text")]
    pub source: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub change_note: Option<String>,
    pub user_sn: Option<i64>,
    #[sea_orm(column_type = "Text")]
    pub create_at: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::tbl_instruction_preset::Entity",
        from = "Column::PresetSn",
        to = "super::tbl_instruction_preset::Column::Sn",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    TblInstructionPreset,
    #[sea_orm(
        belongs_to = "super::tbl_user::Entity",
        from = "Column::UserSn",
        to = "super::tbl_user::Column::Sn",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    TblUser,
}

impl Related<super::tbl_instruction_preset::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblInstructionPreset.def()
    }
}

impl Related<super::tbl_user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblUser.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
