//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, serde :: Serialize)]
#[sea_orm(table_name = "tbl_context_source")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub sn: i64,
    pub manifest_sn: i64,
    #[sea_orm(column_type = "Text")]
    pub kind: String,
    #[sea_orm(column_type = "Text")]
    pub ref_label: String,
    pub ref_sn: Option<i64>,
    pub token_count: i64,
    pub is_repeat: i64,
    pub sort: i64,
    #[sea_orm(column_type = "Text")]
    pub create_at: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::tbl_context_manifest::Entity",
        from = "Column::ManifestSn",
        to = "super::tbl_context_manifest::Column::Sn",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    TblContextManifest,
}

impl Related<super::tbl_context_manifest::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblContextManifest.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
