//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, serde :: Serialize)]
#[sea_orm(table_name = "tbl_project")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub sn: i64,
    pub workspace_sn: i64,
    pub team_sn: Option<i64>,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub repo_name: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub repo_path: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub default_branch: String,
    pub next_num: i64,
    pub is_github_import: i64,
    #[sea_orm(column_type = "Text", nullable)]
    pub import_label: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub orch_mode: Option<String>,
    pub timer_sec: Option<i64>,
    pub is_pause_on_view: Option<i64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub level_json: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub guard_json: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub status: String,
    pub sort: i64,
    #[sea_orm(column_type = "Text")]
    pub create_at: String,
    #[sea_orm(column_type = "Text")]
    pub update_at: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::tbl_ask::Entity")]
    TblAsk,
    #[sea_orm(has_many = "super::tbl_contract::Entity")]
    TblContract,
    #[sea_orm(has_many = "super::tbl_conversation::Entity")]
    TblConversation,
    #[sea_orm(has_many = "super::tbl_diagram_node::Entity")]
    TblDiagramNode,
    #[sea_orm(has_many = "super::tbl_diagram_view::Entity")]
    TblDiagramView,
    #[sea_orm(has_many = "super::tbl_instruction_preset::Entity")]
    TblInstructionPreset,
    #[sea_orm(has_many = "super::tbl_interaction::Entity")]
    TblInteraction,
    #[sea_orm(has_many = "super::tbl_issue::Entity")]
    TblIssue,
    #[sea_orm(has_many = "super::tbl_label::Entity")]
    TblLabel,
    #[sea_orm(has_many = "super::tbl_log_activity::Entity")]
    TblLogActivity,
    #[sea_orm(has_many = "super::tbl_log_event::Entity")]
    TblLogEvent,
    #[sea_orm(has_many = "super::tbl_run::Entity")]
    TblRun,
    #[sea_orm(has_many = "super::tbl_task::Entity")]
    TblTask,
    #[sea_orm(
        belongs_to = "super::tbl_team::Entity",
        from = "Column::TeamSn",
        to = "super::tbl_team::Column::Sn",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    TblTeam,
    #[sea_orm(
        belongs_to = "super::tbl_workspace::Entity",
        from = "Column::WorkspaceSn",
        to = "super::tbl_workspace::Column::Sn",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    TblWorkspace,
}

impl Related<super::tbl_ask::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblAsk.def()
    }
}

impl Related<super::tbl_contract::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblContract.def()
    }
}

impl Related<super::tbl_conversation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblConversation.def()
    }
}

impl Related<super::tbl_diagram_node::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblDiagramNode.def()
    }
}

impl Related<super::tbl_diagram_view::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblDiagramView.def()
    }
}

impl Related<super::tbl_instruction_preset::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblInstructionPreset.def()
    }
}

impl Related<super::tbl_interaction::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblInteraction.def()
    }
}

impl Related<super::tbl_issue::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblIssue.def()
    }
}

impl Related<super::tbl_label::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblLabel.def()
    }
}

impl Related<super::tbl_log_activity::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblLogActivity.def()
    }
}

impl Related<super::tbl_log_event::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblLogEvent.def()
    }
}

impl Related<super::tbl_run::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblRun.def()
    }
}

impl Related<super::tbl_task::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblTask.def()
    }
}

impl Related<super::tbl_team::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblTeam.def()
    }
}

impl Related<super::tbl_workspace::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblWorkspace.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
