//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, serde :: Serialize)]
#[sea_orm(table_name = "tbl_issue")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub sn: i64,
    pub project_sn: i64,
    pub parent_sn: Option<i64>,
    pub num: i64,
    #[sea_orm(column_type = "Text")]
    pub title: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub body: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub status: String,
    #[sea_orm(column_type = "Text")]
    pub source: String,
    pub github_number: Option<i64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub github_url: Option<String>,
    pub user_sn: Option<i64>,
    #[sea_orm(column_type = "Text")]
    pub create_at: String,
    #[sea_orm(column_type = "Text")]
    pub update_at: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub close_at: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::tbl_interaction::Entity")]
    TblInteraction,
    #[sea_orm(
        belongs_to = "Entity",
        from = "Column::ParentSn",
        to = "Column::Sn",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    SelfRef,
    #[sea_orm(has_many = "super::tbl_map_issue_label::Entity")]
    TblMapIssueLabel,
    #[sea_orm(has_many = "super::tbl_orch_proposal::Entity")]
    TblOrchProposal,
    #[sea_orm(
        belongs_to = "super::tbl_project::Entity",
        from = "Column::ProjectSn",
        to = "super::tbl_project::Column::Sn",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    TblProject,
    #[sea_orm(has_many = "super::tbl_task::Entity")]
    TblTask,
    #[sea_orm(
        belongs_to = "super::tbl_user::Entity",
        from = "Column::UserSn",
        to = "super::tbl_user::Column::Sn",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    TblUser,
}

impl Related<super::tbl_interaction::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblInteraction.def()
    }
}

impl Related<super::tbl_map_issue_label::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblMapIssueLabel.def()
    }
}

impl Related<super::tbl_orch_proposal::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblOrchProposal.def()
    }
}

impl Related<super::tbl_project::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblProject.def()
    }
}

impl Related<super::tbl_task::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblTask.def()
    }
}

impl Related<super::tbl_user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblUser.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
