//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, serde :: Serialize)]
#[sea_orm(table_name = "tbl_map_task_label")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub sn: i64,
    pub task_sn: i64,
    pub label_sn: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::tbl_label::Entity",
        from = "Column::LabelSn",
        to = "super::tbl_label::Column::Sn",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    TblLabel,
    #[sea_orm(
        belongs_to = "super::tbl_task::Entity",
        from = "Column::TaskSn",
        to = "super::tbl_task::Column::Sn",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    TblTask,
}

impl Related<super::tbl_label::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblLabel.def()
    }
}

impl Related<super::tbl_task::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblTask.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
