//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, serde :: Serialize)]
#[sea_orm(table_name = "tbl_map_runtime_connection")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub sn: i64,
    pub runtime_sn: i64,
    pub connection_sn: i64,
    #[sea_orm(column_type = "Text", nullable)]
    pub connect_method: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub create_at: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::tbl_connection::Entity",
        from = "Column::ConnectionSn",
        to = "super::tbl_connection::Column::Sn",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    TblConnection,
    #[sea_orm(
        belongs_to = "super::tbl_runtime::Entity",
        from = "Column::RuntimeSn",
        to = "super::tbl_runtime::Column::Sn",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    TblRuntime,
}

impl Related<super::tbl_connection::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblConnection.def()
    }
}

impl Related<super::tbl_runtime::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblRuntime.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
