//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, serde :: Serialize)]
#[sea_orm(table_name = "tbl_member")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub sn: i64,
    pub team_sn: i64,
    pub profile_sn: i64,
    pub template_sn: Option<i64>,
    pub template_version: Option<i64>,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub role_name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub icon: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub color: Option<String>,
    pub is_orch: i64,
    #[sea_orm(column_type = "Text")]
    pub status: String,
    #[sea_orm(column_type = "Text")]
    pub first_task_mode: String,
    pub sort: i64,
    #[sea_orm(column_type = "Text")]
    pub create_at: String,
    #[sea_orm(column_type = "Text")]
    pub update_at: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::tbl_agent_profile::Entity",
        from = "Column::ProfileSn",
        to = "super::tbl_agent_profile::Column::Sn",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    TblAgentProfile,
    #[sea_orm(has_many = "super::tbl_ask::Entity")]
    TblAsk,
    #[sea_orm(has_many = "super::tbl_log_event::Entity")]
    TblLogEvent,
    #[sea_orm(has_many = "super::tbl_message::Entity")]
    TblMessage,
    #[sea_orm(has_many = "super::tbl_notification::Entity")]
    TblNotification,
    #[sea_orm(has_many = "super::tbl_session::Entity")]
    TblSession,
    #[sea_orm(has_many = "super::tbl_task::Entity")]
    TblTask,
    #[sea_orm(
        belongs_to = "super::tbl_team::Entity",
        from = "Column::TeamSn",
        to = "super::tbl_team::Column::Sn",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    TblTeam,
    #[sea_orm(
        belongs_to = "super::tbl_template::Entity",
        from = "Column::TemplateSn",
        to = "super::tbl_template::Column::Sn",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    TblTemplate,
}

impl Related<super::tbl_agent_profile::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblAgentProfile.def()
    }
}

impl Related<super::tbl_ask::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblAsk.def()
    }
}

impl Related<super::tbl_log_event::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblLogEvent.def()
    }
}

impl Related<super::tbl_message::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblMessage.def()
    }
}

impl Related<super::tbl_notification::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblNotification.def()
    }
}

impl Related<super::tbl_session::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblSession.def()
    }
}

impl Related<super::tbl_task::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblTask.def()
    }
}

impl Related<super::tbl_team::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblTeam.def()
    }
}

impl Related<super::tbl_template::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblTemplate.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
