//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, serde :: Serialize)]
#[sea_orm(table_name = "tbl_log_event")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub sn: i64,
    pub workspace_sn: i64,
    pub project_sn: Option<i64>,
    #[sea_orm(column_type = "Text")]
    pub aggregate_type: String,
    pub aggregate_sn: i64,
    pub seq: i64,
    #[sea_orm(column_type = "Text")]
    pub event_type: String,
    pub event_version: i64,
    #[sea_orm(column_type = "Text")]
    pub payload_json: String,
    #[sea_orm(column_type = "Text", nullable, unique_key = "ux_event_command")]
    pub command_id: Option<String>,
    #[sea_orm(unique_key = "ux_event_command")]
    pub command_idx: i64,
    #[sea_orm(column_type = "Text")]
    pub actor_type: String,
    pub user_sn: Option<i64>,
    pub member_sn: Option<i64>,
    pub run_sn: Option<i64>,
    #[sea_orm(column_type = "Text")]
    pub create_at: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::tbl_ask::Entity")]
    TblAsk,
    #[sea_orm(has_many = "super::tbl_interaction::Entity")]
    TblInteraction,
    #[sea_orm(
        belongs_to = "super::tbl_member::Entity",
        from = "Column::MemberSn",
        to = "super::tbl_member::Column::Sn",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    TblMember,
    #[sea_orm(has_many = "super::tbl_notification::Entity")]
    TblNotification,
    #[sea_orm(
        belongs_to = "super::tbl_project::Entity",
        from = "Column::ProjectSn",
        to = "super::tbl_project::Column::Sn",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    TblProject,
    #[sea_orm(
        belongs_to = "super::tbl_run::Entity",
        from = "Column::RunSn",
        to = "super::tbl_run::Column::Sn",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    TblRun,
    #[sea_orm(
        belongs_to = "super::tbl_user::Entity",
        from = "Column::UserSn",
        to = "super::tbl_user::Column::Sn",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    TblUser,
    #[sea_orm(
        belongs_to = "super::tbl_workspace::Entity",
        from = "Column::WorkspaceSn",
        to = "super::tbl_workspace::Column::Sn",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    TblWorkspace,
}

impl Related<super::tbl_ask::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblAsk.def()
    }
}

impl Related<super::tbl_interaction::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblInteraction.def()
    }
}

impl Related<super::tbl_member::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblMember.def()
    }
}

impl Related<super::tbl_notification::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblNotification.def()
    }
}

impl Related<super::tbl_project::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblProject.def()
    }
}

impl Related<super::tbl_run::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblRun.def()
    }
}

impl Related<super::tbl_user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblUser.def()
    }
}

impl Related<super::tbl_workspace::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblWorkspace.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
