//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, serde :: Serialize)]
#[sea_orm(table_name = "tbl_user")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub sn: i64,
    #[sea_orm(column_type = "Text", nullable, unique)]
    pub email: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub password_hash: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub initial: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub ui_language: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub task_view_json: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub status: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub last_login_at: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub create_at: String,
    #[sea_orm(column_type = "Text")]
    pub update_at: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::tbl_ask::Entity")]
    TblAsk,
    #[sea_orm(has_many = "super::tbl_attachment::Entity")]
    TblAttachment,
    #[sea_orm(has_many = "super::tbl_connection::Entity")]
    TblConnection,
    #[sea_orm(has_many = "super::tbl_diagram::Entity")]
    TblDiagram,
    #[sea_orm(has_many = "super::tbl_instruction_preset::Entity")]
    TblInstructionPreset,
    #[sea_orm(has_many = "super::tbl_interaction::Entity")]
    TblInteraction,
    #[sea_orm(has_many = "super::tbl_issue::Entity")]
    TblIssue,
    #[sea_orm(has_many = "super::tbl_log_event::Entity")]
    TblLogEvent,
    #[sea_orm(has_many = "super::tbl_notification::Entity")]
    TblNotification,
    #[sea_orm(has_many = "super::tbl_task::Entity")]
    TblTask,
    #[sea_orm(has_many = "super::tbl_template::Entity")]
    TblTemplate,
    #[sea_orm(has_many = "super::tbl_workspace::Entity")]
    TblWorkspace,
}

impl Related<super::tbl_ask::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblAsk.def()
    }
}

impl Related<super::tbl_attachment::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblAttachment.def()
    }
}

impl Related<super::tbl_connection::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblConnection.def()
    }
}

impl Related<super::tbl_diagram::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblDiagram.def()
    }
}

impl Related<super::tbl_instruction_preset::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblInstructionPreset.def()
    }
}

impl Related<super::tbl_interaction::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblInteraction.def()
    }
}

impl Related<super::tbl_issue::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblIssue.def()
    }
}

impl Related<super::tbl_log_event::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblLogEvent.def()
    }
}

impl Related<super::tbl_notification::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblNotification.def()
    }
}

impl Related<super::tbl_task::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblTask.def()
    }
}

impl Related<super::tbl_template::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblTemplate.def()
    }
}

impl Related<super::tbl_workspace::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblWorkspace.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
