//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, serde :: Serialize)]
#[sea_orm(table_name = "tbl_map_fallback")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub sn: i64,
    #[sea_orm(unique_key = "ux_fallback_sort")]
    pub profile_sn: i64,
    #[sea_orm(unique_key = "ux_fallback_sort")]
    pub runtime_sn: i64,
    pub connection_sn: i64,
    pub model_sn: Option<i64>,
    #[sea_orm(unique_key = "ux_fallback_sort")]
    pub sort: i64,
    #[sea_orm(column_type = "Text", nullable)]
    pub switch_rule: Option<String>,
    pub max_level: Option<i64>,
    #[sea_orm(column_type = "Text")]
    pub create_at: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::tbl_agent_profile::Entity",
        from = "Column::ProfileSn",
        to = "super::tbl_agent_profile::Column::Sn",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    TblAgentProfile,
    #[sea_orm(
        belongs_to = "super::tbl_connection::Entity",
        from = "Column::ConnectionSn",
        to = "super::tbl_connection::Column::Sn",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    TblConnection,
    #[sea_orm(
        belongs_to = "super::tbl_model::Entity",
        from = "Column::ModelSn",
        to = "super::tbl_model::Column::Sn",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    TblModel,
    #[sea_orm(
        belongs_to = "super::tbl_runtime::Entity",
        from = "Column::RuntimeSn",
        to = "super::tbl_runtime::Column::Sn",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    TblRuntime,
}

impl Related<super::tbl_agent_profile::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblAgentProfile.def()
    }
}

impl Related<super::tbl_connection::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblConnection.def()
    }
}

impl Related<super::tbl_model::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblModel.def()
    }
}

impl Related<super::tbl_runtime::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblRuntime.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
