//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, serde :: Serialize)]
#[sea_orm(table_name = "tbl_report_item")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub sn: i64,
    pub run_sn: i64,
    pub task_sn: i64,
    #[sea_orm(column_type = "Text")]
    pub kind: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub ref_key: Option<String>,
    pub criterion_sn: Option<i64>,
    #[sea_orm(column_type = "Text")]
    pub code: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub value: Option<String>,
    pub target_task_sn: Option<i64>,
    pub contract_sn: Option<i64>,
    pub is_routed: i64,
    #[sea_orm(column_type = "Text")]
    pub create_at: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::tbl_contract::Entity",
        from = "Column::ContractSn",
        to = "super::tbl_contract::Column::Sn",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    TblContract,
    #[sea_orm(
        belongs_to = "super::tbl_run::Entity",
        from = "Column::RunSn",
        to = "super::tbl_run::Column::Sn",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    TblRun,
    #[sea_orm(
        belongs_to = "super::tbl_task::Entity",
        from = "Column::TargetTaskSn",
        to = "super::tbl_task::Column::Sn",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    TblTask2,
    #[sea_orm(
        belongs_to = "super::tbl_task::Entity",
        from = "Column::TaskSn",
        to = "super::tbl_task::Column::Sn",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    TblTask1,
    #[sea_orm(
        belongs_to = "super::tbl_task_criterion::Entity",
        from = "Column::CriterionSn",
        to = "super::tbl_task_criterion::Column::Sn",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    TblTaskCriterion,
}

impl Related<super::tbl_contract::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblContract.def()
    }
}

impl Related<super::tbl_run::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblRun.def()
    }
}

impl Related<super::tbl_task_criterion::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblTaskCriterion.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
