//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, serde :: Serialize)]
#[sea_orm(table_name = "tbl_session")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub sn: i64,
    pub run_sn: i64,
    #[sea_orm(unique_key = "ux_session_num")]
    pub member_sn: i64,
    #[sea_orm(unique_key = "ux_session_num")]
    pub num: i64,
    #[sea_orm(column_type = "Text", nullable)]
    pub provider_session_id: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub status: String,
    pub is_resumed: i64,
    pub bootstrap_token: i64,
    #[sea_orm(column_type = "Text", nullable)]
    pub rotate_reason: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub start_at: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub end_at: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::tbl_context_manifest::Entity")]
    TblContextManifest,
    #[sea_orm(has_many = "super::tbl_log_run::Entity")]
    TblLogRun,
    #[sea_orm(has_many = "super::tbl_log_token::Entity")]
    TblLogToken,
    #[sea_orm(
        belongs_to = "super::tbl_member::Entity",
        from = "Column::MemberSn",
        to = "super::tbl_member::Column::Sn",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    TblMember,
    #[sea_orm(
        belongs_to = "super::tbl_run::Entity",
        from = "Column::RunSn",
        to = "super::tbl_run::Column::Sn",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    TblRun,
}

impl Related<super::tbl_context_manifest::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblContextManifest.def()
    }
}

impl Related<super::tbl_log_run::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblLogRun.def()
    }
}

impl Related<super::tbl_log_token::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblLogToken.def()
    }
}

impl Related<super::tbl_member::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblMember.def()
    }
}

impl Related<super::tbl_run::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblRun.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
