//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, serde :: Serialize)]
#[sea_orm(table_name = "tbl_mcp")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub sn: i64,
    pub wid: i64,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub tool_count: i64,
    pub token_cost: i64,
    #[sea_orm(column_type = "Text")]
    pub install_status: String,
    pub is_auth_required: i64,
    #[sea_orm(column_type = "Text")]
    pub auth_status: String,
    #[sea_orm(column_type = "Text")]
    pub health: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub config_json: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub check_at: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub create_at: String,
    #[sea_orm(column_type = "Text")]
    pub update_at: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::tbl_map_profile_mcp::Entity")]
    TblMapProfileMcp,
    #[sea_orm(
        belongs_to = "super::tbl_workspace::Entity",
        from = "Column::Wid",
        to = "super::tbl_workspace::Column::Sn",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    TblWorkspace,
}

impl Related<super::tbl_map_profile_mcp::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblMapProfileMcp.def()
    }
}

impl Related<super::tbl_workspace::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblWorkspace.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
