//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, serde :: Serialize)]
#[sea_orm(table_name = "tbl_task")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub sn: i64,
    pub project_sn: i64,
    pub issue_sn: Option<i64>,
    pub member_sn: Option<i64>,
    pub num: i64,
    #[sea_orm(column_type = "Text")]
    pub title: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub status: String,
    pub priority: i64,
    #[sea_orm(column_type = "Text", nullable)]
    pub assign_by: Option<String>,
    pub queue_sort: Option<i64>,
    pub estimate_min: Option<i64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub eta_at: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub block_reason: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub branch: Option<String>,
    pub commit_count: i64,
    pub pr_number: Option<i64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub pr_status: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub create_by: String,
    pub uid: Option<i64>,
    #[sea_orm(column_type = "Text")]
    pub create_at: String,
    #[sea_orm(column_type = "Text")]
    pub update_at: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub start_at: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub done_at: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::tbl_approval::Entity")]
    TblApproval,
    #[sea_orm(has_many = "super::tbl_contract::Entity")]
    TblContract,
    #[sea_orm(has_many = "super::tbl_decision::Entity")]
    TblDecision,
    #[sea_orm(has_many = "super::tbl_interaction::Entity")]
    TblInteraction,
    #[sea_orm(
        belongs_to = "super::tbl_issue::Entity",
        from = "Column::IssueSn",
        to = "super::tbl_issue::Column::Sn",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    TblIssue,
    #[sea_orm(has_many = "super::tbl_log_activity::Entity")]
    TblLogActivity,
    #[sea_orm(has_many = "super::tbl_map_task_contract::Entity")]
    TblMapTaskContract,
    #[sea_orm(has_many = "super::tbl_map_task_label::Entity")]
    TblMapTaskLabel,
    #[sea_orm(
        belongs_to = "super::tbl_member::Entity",
        from = "Column::MemberSn",
        to = "super::tbl_member::Column::Sn",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    TblMember,
    #[sea_orm(has_many = "super::tbl_message::Entity")]
    TblMessage,
    #[sea_orm(has_many = "super::tbl_orch_proposal::Entity")]
    TblOrchProposal,
    #[sea_orm(
        belongs_to = "super::tbl_project::Entity",
        from = "Column::ProjectSn",
        to = "super::tbl_project::Column::Sn",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    TblProject,
    #[sea_orm(has_many = "super::tbl_review::Entity")]
    TblReview,
    #[sea_orm(has_many = "super::tbl_run::Entity")]
    TblRun,
    #[sea_orm(has_many = "super::tbl_task_criterion::Entity")]
    TblTaskCriterion,
    #[sea_orm(
        belongs_to = "super::tbl_user::Entity",
        from = "Column::Uid",
        to = "super::tbl_user::Column::Uid",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    TblUser,
}

impl Related<super::tbl_approval::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblApproval.def()
    }
}

impl Related<super::tbl_contract::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblContract.def()
    }
}

impl Related<super::tbl_decision::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblDecision.def()
    }
}

impl Related<super::tbl_interaction::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblInteraction.def()
    }
}

impl Related<super::tbl_issue::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblIssue.def()
    }
}

impl Related<super::tbl_log_activity::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblLogActivity.def()
    }
}

impl Related<super::tbl_map_task_contract::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblMapTaskContract.def()
    }
}

impl Related<super::tbl_map_task_label::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblMapTaskLabel.def()
    }
}

impl Related<super::tbl_member::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblMember.def()
    }
}

impl Related<super::tbl_message::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblMessage.def()
    }
}

impl Related<super::tbl_orch_proposal::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblOrchProposal.def()
    }
}

impl Related<super::tbl_project::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblProject.def()
    }
}

impl Related<super::tbl_review::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblReview.def()
    }
}

impl Related<super::tbl_run::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblRun.def()
    }
}

impl Related<super::tbl_task_criterion::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblTaskCriterion.def()
    }
}

impl Related<super::tbl_user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblUser.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
