//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, serde :: Serialize)]
#[sea_orm(table_name = "tbl_instruction_preset")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub sn: i64,
    pub workspace_sn: i64,
    pub project_sn: Option<i64>,
    #[sea_orm(column_type = "Text")]
    pub kind: String,
    #[sea_orm(column_type = "Text")]
    pub preset_key: String,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub version: i64,
    pub limit_tok: i64,
    pub is_builtin: i64,
    pub is_locked: i64,
    pub is_default: i64,
    pub copy_from_sn: Option<i64>,
    #[sea_orm(column_type = "Text")]
    pub status: String,
    pub user_sn: Option<i64>,
    #[sea_orm(column_type = "Text")]
    pub create_at: String,
    #[sea_orm(column_type = "Text")]
    pub update_at: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "Entity",
        from = "Column::CopyFromSn",
        to = "Column::Sn",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    SelfRef,
    #[sea_orm(has_many = "super::tbl_instruction_preset_version::Entity")]
    TblInstructionPresetVersion,
    #[sea_orm(has_many = "super::tbl_map_profile_preset::Entity")]
    TblMapProfilePreset,
    #[sea_orm(
        belongs_to = "super::tbl_project::Entity",
        from = "Column::ProjectSn",
        to = "super::tbl_project::Column::Sn",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    TblProject,
    #[sea_orm(
        belongs_to = "super::tbl_user::Entity",
        from = "Column::UserSn",
        to = "super::tbl_user::Column::Sn",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    TblUser,
    #[sea_orm(
        belongs_to = "super::tbl_workspace::Entity",
        from = "Column::WorkspaceSn",
        to = "super::tbl_workspace::Column::Sn",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    TblWorkspace,
}

impl Related<super::tbl_instruction_preset_version::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblInstructionPresetVersion.def()
    }
}

impl Related<super::tbl_map_profile_preset::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblMapProfilePreset.def()
    }
}

impl Related<super::tbl_project::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblProject.def()
    }
}

impl Related<super::tbl_user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblUser.def()
    }
}

impl Related<super::tbl_workspace::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblWorkspace.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
