//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, serde :: Serialize)]
#[sea_orm(table_name = "tbl_workspace")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub sn: i64,
    pub user_sn: i64,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub default_repo: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub timezone: String,
    #[sea_orm(column_type = "Text")]
    pub ui_language: String,
    #[sea_orm(column_type = "Text")]
    pub report_language: String,
    #[sea_orm(column_type = "Text")]
    pub commit_language: String,
    #[sea_orm(column_type = "Text")]
    pub date_format: String,
    #[sea_orm(column_type = "Text")]
    pub theme: String,
    pub retention_run_log_day: i64,
    pub retention_token_day: i64,
    pub retention_decision_day: i64,
    #[sea_orm(column_type = "Text")]
    pub github_mode: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub github_account: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub github_repo_scope: Option<String>,
    pub max_concurrent_run: i64,
    pub run_timeout_min: i64,
    #[sea_orm(column_type = "Text")]
    pub workdir_mode: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub workdir_root: Option<String>,
    pub worktree_keep_hour: i64,
    #[sea_orm(column_type = "Text", nullable)]
    pub detect_path: Option<String>,
    pub is_network_sandbox: i64,
    pub is_runtime_auto_update: i64,
    pub is_skill_scan_required: i64,
    pub is_skill_approval: i64,
    pub is_skill_pin_version: i64,
    pub is_skill_update_notify: i64,
    #[sea_orm(column_type = "Text", nullable)]
    pub dnd_start: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub dnd_end: Option<String>,
    pub is_dnd_weekend: i64,
    pub dnd_bypass_level: i64,
    #[sea_orm(column_type = "Text", nullable)]
    pub daily_summary_time: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub channel_json: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub notify_json: Option<String>,
    pub is_onboarded: i64,
    #[sea_orm(column_type = "Text")]
    pub create_at: String,
    #[sea_orm(column_type = "Text")]
    pub update_at: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::tbl_agent_profile::Entity")]
    TblAgentProfile,
    #[sea_orm(has_many = "super::tbl_connection::Entity")]
    TblConnection,
    #[sea_orm(has_many = "super::tbl_instruction_preset::Entity")]
    TblInstructionPreset,
    #[sea_orm(has_many = "super::tbl_log_audit::Entity")]
    TblLogAudit,
    #[sea_orm(has_many = "super::tbl_log_event::Entity")]
    TblLogEvent,
    #[sea_orm(has_many = "super::tbl_mcp::Entity")]
    TblMcp,
    #[sea_orm(has_many = "super::tbl_notification::Entity")]
    TblNotification,
    #[sea_orm(has_many = "super::tbl_project::Entity")]
    TblProject,
    #[sea_orm(has_many = "super::tbl_report_form::Entity")]
    TblReportForm,
    #[sea_orm(has_many = "super::tbl_runtime::Entity")]
    TblRuntime,
    #[sea_orm(has_many = "super::tbl_skill::Entity")]
    TblSkill,
    #[sea_orm(has_many = "super::tbl_skill_source::Entity")]
    TblSkillSource,
    #[sea_orm(has_many = "super::tbl_team::Entity")]
    TblTeam,
    #[sea_orm(has_many = "super::tbl_template::Entity")]
    TblTemplate,
    #[sea_orm(
        belongs_to = "super::tbl_user::Entity",
        from = "Column::UserSn",
        to = "super::tbl_user::Column::Sn",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    TblUser,
}

impl Related<super::tbl_agent_profile::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblAgentProfile.def()
    }
}

impl Related<super::tbl_connection::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblConnection.def()
    }
}

impl Related<super::tbl_instruction_preset::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblInstructionPreset.def()
    }
}

impl Related<super::tbl_log_audit::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblLogAudit.def()
    }
}

impl Related<super::tbl_log_event::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblLogEvent.def()
    }
}

impl Related<super::tbl_mcp::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblMcp.def()
    }
}

impl Related<super::tbl_notification::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblNotification.def()
    }
}

impl Related<super::tbl_project::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblProject.def()
    }
}

impl Related<super::tbl_report_form::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblReportForm.def()
    }
}

impl Related<super::tbl_runtime::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblRuntime.def()
    }
}

impl Related<super::tbl_skill::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblSkill.def()
    }
}

impl Related<super::tbl_skill_source::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblSkillSource.def()
    }
}

impl Related<super::tbl_team::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblTeam.def()
    }
}

impl Related<super::tbl_template::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblTemplate.def()
    }
}

impl Related<super::tbl_user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblUser.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
