//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, serde :: Serialize)]
#[sea_orm(table_name = "tbl_task_view")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub sn: i64,
    pub workspace_sn: i64,
    pub user_sn: i64,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub filter_json: String,
    pub sort: i64,
    #[sea_orm(column_type = "Text")]
    pub create_at: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::tbl_user::Entity",
        from = "Column::UserSn",
        to = "super::tbl_user::Column::Sn",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    TblUser,
    #[sea_orm(
        belongs_to = "super::tbl_workspace::Entity",
        from = "Column::WorkspaceSn",
        to = "super::tbl_workspace::Column::Sn",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    TblWorkspace,
}

impl Related<super::tbl_user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblUser.def()
    }
}

impl Related<super::tbl_workspace::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblWorkspace.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
