//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, serde :: Serialize)]
#[sea_orm(table_name = "tbl_agent_profile")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub sn: i64,
    pub workspace_sn: i64,
    #[sea_orm(column_type = "Text")]
    pub kind: String,
    pub runtime_sn: Option<i64>,
    pub connection_sn: Option<i64>,
    pub model_sn: Option<i64>,
    #[sea_orm(column_type = "Text")]
    pub effort: String,
    #[sea_orm(column_type = "Text")]
    pub session_mode: String,
    #[sea_orm(column_type = "Text")]
    pub repo_rule_mode: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub workdir: Option<String>,
    pub trust_level: i64,
    #[sea_orm(column_type = "Text", nullable)]
    pub github_mode: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub network_mode: String,
    pub run_token_limit: Option<i64>,
    pub context_warn_percent: i64,
    pub run_time_limit_min: Option<i64>,
    pub auto_retry_max: i64,
    #[sea_orm(column_type = "Text")]
    pub create_at: String,
    #[sea_orm(column_type = "Text")]
    pub update_at: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::tbl_connection::Entity",
        from = "Column::ConnectionSn",
        to = "super::tbl_connection::Column::Sn",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    TblConnection,
    #[sea_orm(has_many = "super::tbl_map_fallback::Entity")]
    TblMapFallback,
    #[sea_orm(has_many = "super::tbl_map_profile_mcp::Entity")]
    TblMapProfileMcp,
    #[sea_orm(has_many = "super::tbl_map_profile_preset::Entity")]
    TblMapProfilePreset,
    #[sea_orm(has_many = "super::tbl_map_profile_skill::Entity")]
    TblMapProfileSkill,
    #[sea_orm(has_many = "super::tbl_member::Entity")]
    TblMember,
    #[sea_orm(
        belongs_to = "super::tbl_model::Entity",
        from = "Column::ModelSn",
        to = "super::tbl_model::Column::Sn",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    TblModel,
    #[sea_orm(has_many = "super::tbl_profile_file::Entity")]
    TblProfileFile,
    #[sea_orm(has_many = "super::tbl_profile_guard::Entity")]
    TblProfileGuard,
    #[sea_orm(has_many = "super::tbl_profile_path::Entity")]
    TblProfilePath,
    #[sea_orm(has_many = "super::tbl_profile_rule::Entity")]
    TblProfileRule,
    #[sea_orm(has_many = "super::tbl_profile_tool::Entity")]
    TblProfileTool,
    #[sea_orm(
        belongs_to = "super::tbl_runtime::Entity",
        from = "Column::RuntimeSn",
        to = "super::tbl_runtime::Column::Sn",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    TblRuntime,
    #[sea_orm(has_many = "super::tbl_template_revision::Entity")]
    TblTemplateRevision,
    #[sea_orm(
        belongs_to = "super::tbl_workspace::Entity",
        from = "Column::WorkspaceSn",
        to = "super::tbl_workspace::Column::Sn",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    TblWorkspace,
}

impl Related<super::tbl_connection::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblConnection.def()
    }
}

impl Related<super::tbl_map_fallback::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblMapFallback.def()
    }
}

impl Related<super::tbl_map_profile_mcp::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblMapProfileMcp.def()
    }
}

impl Related<super::tbl_map_profile_preset::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblMapProfilePreset.def()
    }
}

impl Related<super::tbl_map_profile_skill::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblMapProfileSkill.def()
    }
}

impl Related<super::tbl_member::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblMember.def()
    }
}

impl Related<super::tbl_model::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblModel.def()
    }
}

impl Related<super::tbl_profile_file::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblProfileFile.def()
    }
}

impl Related<super::tbl_profile_guard::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblProfileGuard.def()
    }
}

impl Related<super::tbl_profile_path::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblProfilePath.def()
    }
}

impl Related<super::tbl_profile_rule::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblProfileRule.def()
    }
}

impl Related<super::tbl_profile_tool::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblProfileTool.def()
    }
}

impl Related<super::tbl_runtime::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblRuntime.def()
    }
}

impl Related<super::tbl_template_revision::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblTemplateRevision.def()
    }
}

impl Related<super::tbl_workspace::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblWorkspace.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
