//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, serde :: Serialize)]
#[sea_orm(table_name = "tbl_log_contract")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub sn: i64,
    pub contract_sn: i64,
    pub version: i64,
    #[sea_orm(column_type = "Text")]
    pub change_code: String,
    #[sea_orm(column_type = "Text")]
    pub delta: String,
    pub run_sn: Option<i64>,
    #[sea_orm(column_type = "Text")]
    pub create_at: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::tbl_contract::Entity",
        from = "Column::ContractSn",
        to = "super::tbl_contract::Column::Sn",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    TblContract,
    #[sea_orm(
        belongs_to = "super::tbl_run::Entity",
        from = "Column::RunSn",
        to = "super::tbl_run::Column::Sn",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    TblRun,
}

impl Related<super::tbl_contract::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblContract.def()
    }
}

impl Related<super::tbl_run::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblRun.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
