//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, serde :: Serialize)]
#[sea_orm(table_name = "tbl_template_revision")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub sn: i64,
    pub template_sn: i64,
    pub profile_sn: i64,
    pub version: i64,
    #[sea_orm(column_type = "Text")]
    pub status: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub note: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub author_type: String,
    pub uid: Option<i64>,
    #[sea_orm(column_type = "Text")]
    pub create_at: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub publish_at: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::tbl_agent_profile::Entity",
        from = "Column::ProfileSn",
        to = "super::tbl_agent_profile::Column::Sn",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    TblAgentProfile,
    #[sea_orm(
        belongs_to = "super::tbl_template::Entity",
        from = "Column::TemplateSn",
        to = "super::tbl_template::Column::Sn",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    TblTemplate,
    #[sea_orm(
        belongs_to = "super::tbl_user::Entity",
        from = "Column::Uid",
        to = "super::tbl_user::Column::Uid",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    TblUser,
}

impl Related<super::tbl_agent_profile::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblAgentProfile.def()
    }
}

impl Related<super::tbl_template::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblTemplate.def()
    }
}

impl Related<super::tbl_user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblUser.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
